package enum

/* This file is automatically generated */

type DocumentType byte

const (
	DocumentNone    DocumentType = 0
	DocumentNoValue DocumentType = 1
	DocumentBill    DocumentType = 2
	DocumentBarcode DocumentType = 3
	DocumentCoupon  DocumentType = 4
)

const (
	DocumentTextNone    = "None"
	DocumentTextNoValue = "NoValue"
	DocumentTextBill    = "Bill"
	DocumentTextBarcode = "Barcode"
	DocumentTextCoupon  = "Coupon"
)

var DocumentMap = map[DocumentType]string{
	DocumentNone:    DocumentTextNone,
	DocumentNoValue: DocumentTextNoValue,
	DocumentBill:    DocumentTextBill,
	DocumentBarcode: DocumentTextBarcode,
	DocumentCoupon:  DocumentTextCoupon,
}

func (obj DocumentType) String() string {
	val, ok := DocumentMap[obj]
	if ok {
		return val
	}
	return "Unknown DocumentType"
}
