package enum

/* This file is automatically generated */

type OrientationType byte

const (
	OrientationRightUp            OrientationType = 0
	OrientationRightDown          OrientationType = 1
	OrientationLeftUp             OrientationType = 2
	OrientationLeftDown           OrientationType = 3
	OrientationUnknownOrientation OrientationType = 4
)

const (
	OrientationTextRightUp            = "RightUp"
	OrientationTextRightDown          = "RightDown"
	OrientationTextLeftUp             = "LeftUp"
	OrientationTextLeftDown           = "LeftDown"
	OrientationTextUnknownOrientation = "UnknownOrientation"
)

var OrientationMap = map[OrientationType]string{
	OrientationRightUp:            OrientationTextRightUp,
	OrientationRightDown:          OrientationTextRightDown,
	OrientationLeftUp:             OrientationTextLeftUp,
	OrientationLeftDown:           OrientationTextLeftDown,
	OrientationUnknownOrientation: OrientationTextUnknownOrientation,
}

func (obj OrientationType) String() string {
	val, ok := OrientationMap[obj]
	if ok {
		return val
	}
	return "Unknown OrientationType"
}
