package enum

/* This file is automatically generated */

type OrientationControlType byte

const (
	OrientationControlFourWay OrientationControlType = 0
	OrientationControlTwoWay  OrientationControlType = 1
	OrientationControlOneWay  OrientationControlType = 2
)

const (
	OrientationControlTextFourWay = "FourWay"
	OrientationControlTextTwoWay  = "TwoWay"
	OrientationControlTextOneWay  = "OneWay"
)

var OrientationControlMap = map[OrientationControlType]string{
	OrientationControlFourWay: OrientationControlTextFourWay,
	OrientationControlTwoWay:  OrientationControlTextTwoWay,
	OrientationControlOneWay:  OrientationControlTextOneWay,
}

func (obj OrientationControlType) String() string {
	val, ok := OrientationControlMap[obj]
	if ok {
		return val
	}
	return "Unknown OrientationControlType"
}
