package enum

/* This file is automatically generated */

type PupExtType byte

const (
	PupExtReturn        PupExtType = 0
	PupExtOutOfService  PupExtType = 1
	PupExtStack         PupExtType = 2
	PupExtStackNoCredit PupExtType = 3
	PupExtWait          PupExtType = 4
	PupExtWaitNoCredit  PupExtType = 5
)

const (
	PupExtTextReturn        = "Return"
	PupExtTextOutOfService  = "OutOfService"
	PupExtTextStack         = "Stack"
	PupExtTextStackNoCredit = "StackNoCredit"
	PupExtTextWait          = "Wait"
	PupExtTextWaitNoCredit  = "WaitNoCredit"
)

var PupExtMap = map[PupExtType]string{
	PupExtReturn:        PupExtTextReturn,
	PupExtOutOfService:  PupExtTextOutOfService,
	PupExtStack:         PupExtTextStack,
	PupExtStackNoCredit: PupExtTextStackNoCredit,
	PupExtWait:          PupExtTextWait,
	PupExtWaitNoCredit:  PupExtTextWaitNoCredit,
}

func (obj PupExtType) String() string {
	val, ok := PupExtMap[obj]
	if ok {
		return val
	}
	return "Unknown PupExtType"
}
