package enum

/* This file is automatically generated */

type StateType byte

const (
	StateEscrow          StateType = 0
	StateStacked         StateType = 1
	StateReturned        StateType = 2
	StateRejected        StateType = 3
	StateStalled         StateType = 4
	StateAccepting       StateType = 5
	StateCalibrateStart  StateType = 6
	StateCalibrating     StateType = 7
	StateConnecting      StateType = 8
	StateDisconnected    StateType = 9
	StateDownloading     StateType = 10
	StateDownloadRestart StateType = 11
	StateDownloadStart   StateType = 12
	StateFailed          StateType = 13
	StateIdling          StateType = 14
	StatePupEscrow       StateType = 15
	StateReturning       StateType = 16
	StateStacking        StateType = 17
)

const (
	StateTextEscrow          = "Escrow"
	StateTextStacked         = "Stacked"
	StateTextReturned        = "Returned"
	StateTextRejected        = "Rejected"
	StateTextStalled         = "Stalled"
	StateTextAccepting       = "Accepting"
	StateTextCalibrateStart  = "CalibrateStart"
	StateTextCalibrating     = "Calibrating"
	StateTextConnecting      = "Connecting"
	StateTextDisconnected    = "Disconnected"
	StateTextDownloading     = "Downloading"
	StateTextDownloadRestart = "DownloadRestart"
	StateTextDownloadStart   = "DownloadStart"
	StateTextFailed          = "Failed"
	StateTextIdling          = "Idling"
	StateTextPupEscrow       = "PupEscrow"
	StateTextReturning       = "Returning"
	StateTextStacking        = "Stacking"
)

var StateMap = map[StateType]string{
	StateEscrow:          StateTextEscrow,
	StateStacked:         StateTextStacked,
	StateReturned:        StateTextReturned,
	StateRejected:        StateTextRejected,
	StateStalled:         StateTextStalled,
	StateAccepting:       StateTextAccepting,
	StateCalibrateStart:  StateTextCalibrateStart,
	StateCalibrating:     StateTextCalibrating,
	StateConnecting:      StateTextConnecting,
	StateDisconnected:    StateTextDisconnected,
	StateDownloading:     StateTextDownloading,
	StateDownloadRestart: StateTextDownloadRestart,
	StateDownloadStart:   StateTextDownloadStart,
	StateFailed:          StateTextFailed,
	StateIdling:          StateTextIdling,
	StatePupEscrow:       StateTextPupEscrow,
	StateReturning:       StateTextReturning,
	StateStacking:        StateTextStacking,
}

func (obj StateType) String() string {
	val, ok := StateMap[obj]
	if ok {
		return val
	}
	return "Unknown StateType"
}
