package enum

/* This file is automatically generated */

type BNFStatusType byte

const (
	BNFStatusUnknown     BNFStatusType = 0
	BNFStatusError       BNFStatusType = 1
	BNFStatusOK          BNFStatusType = 2
	BNFStatusNotAttached BNFStatusType = 3
)

const (
	BNFStatusTextUnknown     = "Unknown"
	BNFStatusTextError       = "Error"
	BNFStatusTextOK          = "OK"
	BNFStatusTextNotAttached = "NotAttached"
)

var BNFStatusMap = map[BNFStatusType]string{
	BNFStatusUnknown:     BNFStatusTextUnknown,
	BNFStatusError:       BNFStatusTextError,
	BNFStatusOK:          BNFStatusTextOK,
	BNFStatusNotAttached: BNFStatusTextNotAttached,
}

func (obj BNFStatusType) String() string {
	val, ok := BNFStatusMap[obj]
	if ok {
		return val
	}
	return "Unknown BNFStatusType"
}
