package consts

/* This file is automatically generated */

type CmdType int

const (
	CmdOmnibus       CmdType = 0x10
	CmdCalibrate     CmdType = 0x40
	CmdFlashDownload CmdType = 0x50
	CmdAuxiliary     CmdType = 0x60
	CmdExpanded      CmdType = 0x70
)

const (
	CmdTextOmnibus       = "Omnibus"
	CmdTextCalibrate     = "Calibrate"
	CmdTextFlashDownload = "FlashDownload"
	CmdTextAuxiliary     = "Auxiliary"
	CmdTextExpanded      = "Expanded"
)

var CmdMap = map[CmdType]string{
	CmdOmnibus:       CmdTextOmnibus,
	CmdCalibrate:     CmdTextCalibrate,
	CmdFlashDownload: CmdTextFlashDownload,
	CmdAuxiliary:     CmdTextAuxiliary,
	CmdExpanded:      CmdTextExpanded,
}

func (obj CmdType) String() string {
	val, ok := CmdMap[obj]
	if ok {
		return val
	}
	return "Unknown CmdType"
}
