package consts

/* This file is automatically generated */

type CmdType byte

const (
	CmdOmnibus       CmdType = 0x10
	CmdRetStatus     CmdType = 0x20
	CmdCalibrate     CmdType = 0x40
	CmdFlashDownload CmdType = 0x50
	CmdAuxiliary     CmdType = 0x60
	CmdExpanded      CmdType = 0x70
)

const (
	CmdTextOmnibus       = "Omnibus"
	CmdTextRetStatus     = "RetStatus"
	CmdTextCalibrate     = "Calibrate"
	CmdTextFlashDownload = "FlashDownload"
	CmdTextAuxiliary     = "Auxiliary"
	CmdTextExpanded      = "Expanded"
)

var CmdMap = map[CmdType]string{
	CmdOmnibus:       CmdTextOmnibus,
	CmdRetStatus:     CmdTextRetStatus,
	CmdCalibrate:     CmdTextCalibrate,
	CmdFlashDownload: CmdTextFlashDownload,
	CmdAuxiliary:     CmdTextAuxiliary,
	CmdExpanded:      CmdTextExpanded,
}

func (obj CmdType) String() string {
	val, ok := CmdMap[obj]
	if ok {
		return val
	}
	return "Unknown CmdType"
}

func (obj CmdType) Byte() byte {
	return byte(obj)
}
