package consts

/* This file is automatically generated */

type DataType byte

const (
	DataSTX     DataType = 0x02
	DataETX     DataType = 0x03
	DataACKMask DataType = 0x06
)

const (
	DataTextSTX     = "STX"
	DataTextETX     = "ETX"
	DataTextACKMask = "ACKMask"
)

var DataMap = map[DataType]string{
	DataSTX:     DataTextSTX,
	DataETX:     DataTextETX,
	DataACKMask: DataTextACKMask,
}

func (obj DataType) String() string {
	val, ok := DataMap[obj]
	if ok {
		return val
	}
	return "Unknown DataType"
}

func (obj DataType) Byte() byte {
	return byte(obj)
}
