name: Go Tests and Benchmarks

on:
  push:
    paths-ignore:
      - '**/*.yml'
      - 'const.go'
      - '**/*.txt'
      - '*.md'
      - '*.pdf'
  pull_request:
    paths-ignore:
      - '**/*.yml'
      - 'const.go'
      - '**/*.txt'
      - '*.md'
      - '*.pdf'

jobs:
  test:
    name: "Test  [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.22.5]
    permissions:
      contents: write

      ########################################################################################################################

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: |
          echo "Running tests..."
          go test -v ./... || exit 1

      - name: Run benchmarks
        run: |
          echo "Running benchmarks..."
          go test -bench . -v ./... || exit 1